# This is a basic workflow to help you get started with Actions

name: CI (FHIR Validation)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
    - 'Resources/**'
    branches-ignore:
    - 'main**'
  pull_request:
    branches:
    - 'main**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validate all resources using Firely Terminal 
  CI_FHIR_VALIDATION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code (PR)
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout code (Main)
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'

      # Java and .NET are already installed on ubuntu-latest
        
      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.6.8
        with:
          PATH_TO_CONFORMANCE_RESOURCES: Resources/fsh-generated/resources/
          DOTNET_VALIDATION_ENABLED: true
          JAVA_VALIDATION_ENABLED: true
          JAVA_VALIDATION_OPTIONS: -allow-example-urls true -output-style compact -html-output validation.html -show-message-ids -language de -jurisdiction de -display-issues-are-warnings -advisor-file validator/advisor.json -resolution-context file:Resources/fsh-generated/resources/
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          SUSHI_ENABLED: true
          SUSHI_OPTIONS: Resources/
          EXPECTED_FAILS: VALIDATION_CONFORMANCE_JAVA VALIDATION_CONFORMANCE_DOTNET

      - name: Convert validation report to Markdown
        run: |
          sudo apt-get install -y pandoc
          echo "## ðŸ¥ FHIR Validation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          pandoc -f html -t markdown_strict validation.html >> $GITHUB_STEP_SUMMARY

      # Upload validation.html as an artifact for later download
      - name: Upload Validation Report
        uses: actions/upload-artifact@v4
        with:
          name: fhir-validation-report
          path: validation.html
          retention-days: 7  # Keep the artifact for 7 days

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions Bot
          committer_email: ActionBot@github.com
          add: 'Resources/fsh-generated/resources/'
          message: auto-generated FHIR files by GitHub Actions (CI FSH to FHIR Validation)
